language: nix
nix: 2.3

script:
    #- nix-shell --run "find . -name '*.nix' -exec nixpkgs-fmt --check {} +;"
    - nix-build -E 'with import <nixpkgs>{}; (callPackage ./nur.nix {})'
    - nix-build -E 'with import <nixpkgs>{}; (callPackage ./default.nix {})'

deploy:
    - provider: script
      script: curl -XPOST https://nur-update.herokuapp.com/update?repo=kampka
      on:
        branch: master
